/*---------------------USER---------------------------*/
export const SET_USER = 'SET_USER'
export const SET_USER_BY_ID = 'SET_USER_BY_ID'
export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const SET_USERS = 'SET_USERS'
export const SET_LOGGED_USER = 'SET_LOGGED_USER'
export const SET_SELECTED_USER = 'SET_SELECTED_USER'
export const MODIFY_USER = 'MODIFY_USER'
export const HANDLE_CHANGE_USER = 'HANDLE_CHANGE_USER'
export const MODIFY_PROFILE = 'MODIFY_PROFILE'
export const HANDLE_USER = 'HANDLE_USER'
export const FILTER_USERS_BY_ID = 'FILTER_USER_BY_ID'
export const HANDLE_ACTIVE_USER = 'HANDLE_ACTIVE_USER'
export const HANDLE_DELETE_USER = 'HANDLE_DELETE_USER'
export const HANDLE_SHOW_USER = 'HANDLE_SHOW_USER'
export const HANDLE_SHOW_ALL_USERS = 'HANDLE_SHOW_ALL_USERS'
/*---------------------FAKTURY------------------------*/
export const SET_FAKTURY = 'SET_FAKTURY'
export const SET_ALL_USER_FAKTURY = 'SET_ALL_USER_FAKTURY'
export const ADD_FAKTURA = 'ADD_FAKTURA'
export const DELETE_FAKTURA = 'DELETE_FAKTURA'
/*---------------------UMOWY--------------------------*/
export const SET_UMOWY = 'SET_UMOWY'
export const SET_ALL_USER_UMOWY = 'SET_ALL_USER_UMOWY'
export const ADD_UMOWA = 'ADD_UMOWA'
/*---------------------ROZLICZENIA--------------------*/
export const SET_IS_ROZLICZ_SHOW = 'SET_IS_ROZLICZ_SHOW'
export const SET_ROZLICZENIA = 'SET_ROZLICZENIA'
export const SET_ROZLICZENIE = 'SET_ROZLICZENIA'
export const SET_ALL_USER_ROZLICZENIA = 'SET_ALL_USER_ROZLICZENIA'
export const HANDLE_CHANGE_ROZLICZENIE = 'HANDLE_CHANGE_ROZLICZENIE'
export const HANDLE_MODIFY_ROZLICZENIA = 'HANDLE_MODIFY_ROZLICZENIA'
export const SAVE_ROZLICZENIE = 'SAVE_ROZLICZENIE'
